"""add anomaly_reason and subscription fields

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-08

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0008'
down_revision: Union[str, None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'subscriptions',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_unique_constraint('uq_subscriptions_user_merchant', 'subscriptions', ['user_id', 'merchant_name'])
    op.add_column('transactions', sa.Column('anomaly_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'anomaly_reason')
    op.drop_constraint('uq_subscriptions_user_merchant', 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'is_active')
    # ### end Alembic commands ###
